### ISSUE TITLE
HW feedback

### ISSUE THREAD

**Issue by rfaroul** [EugeneKramer/RCB#1]
Great job, overall. A few tips on structuring your code:

When you have a chance, edit your git/github repo so that each hw assignment is in its own repo. If you don't, it makes it really difficult for collaborators to clone your repo and edit/contribute to your code. Each HW assignment (aka project) should be in its own repo.

Your CSS looks great. Your images are crisp and clear. You may be interested in the never-ending discussions about whether png or jpeg files are better for the web. 

Put your js code in a different file (not in your html files). You can put it in the game.js file that's in the assets/javascript folder. In your html file, you could add a script tag at the end of the file, just before the closing </body> tag. It would look like this: <script src='javascript/game.js'></script>

**Comment by EugeneKramer** [comment]
@rfaroul Thanks for the feedback. I'll submit future assignments with their own repo, and I'll break out the js into a separate file.
